# pylint: disable=missing-module-docstring, missing-function-docstring, missing-class-docstring, unused-argument
from typing import Tuple, Sequence

AST_OFFSET: int

def set_ephe_path(_path: str) -> None: ...
def julday(year: int, month: int, day: int, hour: float = ...) -> float: ...
def revjul(jd: float) -> Tuple[int, int, int, float]: ...
def calc_ut(jd_ut: float, body: int, flags: int = ...) -> Tuple[Sequence[float], int]: ...
def lun_eclipse_when(jd_ut: float) -> Tuple[int, Tuple[float, ...], Tuple[float, ...], Tuple[float, ...], Tuple[float, ...]]: ...
def houses(jd_ut: float, lat: float, lon: float, hsys: bytes) -> Tuple[Sequence[float], Sequence[float]]: ...
